### ISSUE TITLE
Nearly 10hrs of backup and not yet finished - is this a normal behaviour?

### ISSUE THREAD

**Issue by AlexStephenLytton** [EideardVMR/unraid-easybackup#2]
Hi Eideard, 

I just installed your Plugin and experienced a - at least it feels to me as a such - strange behaviour of the plugin.

I started a backup of my freshly installed Ubuntu Server VM which has a VDISK size of 64G and after nearly 10 hrs it's not finished yet. 

![Screenshot 2023-09-28 185459](https://github.com/EideardVMR/unraid-easybackup/assets/5282456/d81f283e-53b2-49c5-9678-8ba76e1e39c8)

![Screenshot 2023-09-28 185544](https://github.com/EideardVMR/unraid-easybackup/assets/5282456/fc2d577e-4846-4127-95bb-d482cced2351)

Shouldn't it be finished after maybe an hour or two?

Greetings,

Alex

**Comment by EideardVMR** [comment]
Hi, thanks for your feedback.
This is absolutely not normal. I assume that the job has stopped running or crashed for some reason.

What are you using as a backup method? Zip?
Zip is slower than the other two methods. For me, a 372GB run takes ~5:30 hours. So 64GB should be done in ~1hr. 

Under /boot/config/plugins/easybackup/ there is an easybackup.log
Would you like to send it to me?

To reset the job, you can delete the jobs.json in the same directory or remove the entry in it. 

In the current version the indication, whether a job runs, is determined exclusively over the jobs.json. An entry is created there at startup and removed again when the job is terminated. However, if the job is abruptly terminated, e.g. by a kill command or because the job was started in a terminal that is closed. Unfortunately, the entry remains. I am working on also being able to determine an active session, but so far this is not yet finished. 

In the terminal you can use "ps aux | grep job.php" to see if the job is still running.
![image](https://github.com/EideardVMR/unraid-easybackup/assets/143615696/d6d3030c-7060-4a32-bc64-56044ae8f252)

**Comment by EideardVMR** [comment]
The problem was related to another problem and should be fixed now.
A check if the job is really still running is not done yet, but if the server is not shut down during work or you remove the job manually, it should not occur again. I will close this task now. Thanks for your support.
