### ISSUE TITLE
Request - USB Flash Backup

### ISSUE THREAD

**Issue by NickBootOne** [EideardVMR/unraid-easybackup#5]
Is it possible to add Flash Backup ?
So that the USB is backed up.
 
If this is possible than i can fully replace "Backup / Restore Appdata" Pugin with EasyBackup.

**Comment by EideardVMR** [comment]
Yes, it is possible.
BUT it is not quite clear to me yet which steps I have to take to create a secure backup. I do not want to offer this function so far, because it is not (or only difficult) for most users to try a restore. With a backup tool for VMs and containers, anyone can simply unpack the backup and manually start it separately to check if the backup is working properly. With a flash backup this is not so easy. Who then relies on the backup and in case of error the backup is faulty has a big problem. Therefore I will implement this function only when I know exactly how this works. 

### Next the following will be implemented:
**Write the last backup to an external disk. Including selected shares**
So you can for example always write a backup to an external disk on sundays which you take to work on mondays and store it there. With two hard disks in alternation you would still have the most necessary data even in case of fire. 

**Restore backups for VMs and containers**
The button already exists, but without any function. I should make up for that.

**Comment by NickBootOne** [comment]
It think my text wasn't clear, but I mean the Flash Backup on unRAID, so that the Bootable USB Drive wil be in an Backup.
But what you mentioned is also a good idea 👌

**Comment by EideardVMR** [comment]
I think I have already understood you correctly.
Unraid does not, as far as I know, create a backup of the flash and store it somewhere. 
So I have to create the backup myself and I have to be sure that it works. But since I don't currently have a device to test it, it will take some time with the function.

It can also be that my text is not quite clear. English writing is sometimes a bit difficult for me, which is why I have to translate some words.

**Comment by NickBootOne** [comment]
No worries @EideardVMR  😉
I thought I typed something wrong 😂

If the option isn't possible you can close this request 👌
It was only a question if it was possible.


If I have a new idea or a other problem I'll drop a new request or issue 😁

**Comment by EideardVMR** [comment]
Since it's not actually a bug, I'll close it for now.
Otherwise it is always above as a bug ;) 

In any case, thank you very much for your support and help with troubleshooting! Since it did not work with the support forum link somehow was already pretty badly talked about the plugin in the forum. The assistance of the community is limited but then also rather on bad talk than on appropriate assistance.

I concentrate on the bug reports here in the repo, that should be enough. Anyone who is seriously interested will find their way here.

**Comment by EideardVMR** [comment]
Hey, good news. If everything works out, I will upload a new version in the days. There will also be the function of flash backup. There is no GUI for the overview yet. But it can be turned on in the settings. It worked for me, as far as I could tell. If you have the opportunity and want to test it I would be grateful for info. BUT it is an experimental function! So please secure you in the meantime on conventional ways your flash drive.

![image](https://github.com/EideardVMR/unraid-easybackup/assets/143615696/13e5213a-325a-4dcd-b4ea-13dde24a9d90)

The GUI will not be faster yet ;) This will be the next construction site.

**Comment by NickBootOne** [comment]
Is the flash backup only triggered with the backup all option or is there some kind of command like backup flash ?

**Comment by EideardVMR** [comment]
The flashbackup is triggered with the backup all command, if enabled. But you can also start only the flash backup manually with backup flash. 

php /usr/local/emhttp/plugins/easybackup/job.php backup flash

There is currently no button to start it.

**Comment by NickBootOne** [comment]
Works like a charm !! 👌

other question.... does the job.php backup also works for only backup appdata
So like job.php backup appdata ?

**Comment by EideardVMR** [comment]
No, you can't do it that way. 
But it is no problem to retrofit it. However, the ignored VMs and containers would be taken into account. If you plan to use the command to unignore them as well, you'd have to put more effort into it. 

You can use this commands:

Backup all enabled types (VM, container, flash) without the ignored ones.:
php /usr/local/emhttp/plugins/easybackup/job.php backup all

Backup of a specific VM (even if Container Backup is disabled or ignored).
php /usr/local/emhttp/plugins/easybackup/job.php backup vm [NAME OF VM]

Backup of a specific container (even if Container Backup is disabled or ignored). However, ignored binds of the container are taken into account!
php /usr/local/emhttp/plugins/easybackup/job.php backup container [NAME OF CONTAINER]

Backup USB Drives:
php /usr/local/emhttp/plugins/easybackup/job.php backup flash

Removes older backups according to the set retention periods. The Flash backup is currently still excluded from this.
php /usr/local/emhttp/plugins/easybackup/job.php cleanup
