### ISSUE TITLE
Plugin is backing up VMs that are disabled

### ISSUE THREAD

**Issue by exico91** [EideardVMR/unraid-easybackup#7]
I dont know why but although i checked the Disable square on all VMs except two the plugin proceed to backup all the VMs anyways ignoring the setting.

![2023-11-26 10_33_42-UNRAIDSRV_easybackup – Mozilla Firefox](https://github.com/EideardVMR/unraid-easybackup/assets/97479177/04529c46-2634-4b18-8477-0740614f8710)

I tried to check all and save, de-check all and save and then check what i do not want to backup but it is ignored

**Comment by EideardVMR** [comment]
Hi, yes this is a bug that still exists, which I am currently fixing.
I am still testing the current version and then a patch will be released. 
It seems to work for me, I would like to test it a little longer, but if it is important to you, I will upload the version right away.

**Comment by exico91** [comment]
Thank you for the quick response.

It is an hassle but not urgent, I can deal with it for now. Better wait for stability

**Comment by EideardVMR** [comment]
Thank you, I have the same problem. One of my VMs cannot be backed up because it does not have a GuestAgent. But it tries anyway. So now I have to test if it works. 1-2 nights then I should know exactly. 

In the short term, there are 2 solutions for you. Maybe one of them is possible:
1: 
Switch off the GuestAgent on the VM. Easybackup will say that the backup has errors, but this is only because it wanted to make a backup and could not. 

2: 
You can also temporarily swap the commands (only worthwhile if you don't have too many VMs/containers)
To do this, enter each VM/container manually:
php /usr/local/emhttp/plugins/easybackup/job.php backup vm "[Name of VM]"
php /usr/local/emhttp/plugins/easybackup/job.php backup container "[Name of Container]"
Don't forget the quotation marks ;)

But as I said, I want the backup to run smoothly for 1-2 nights, then I'll do a release.

**Comment by EideardVMR** [comment]
I have uploaded the update. The error should now be fixed. It works for me. If there are any further problems, please reopen the Issue again, I'll take care of it.
